adclass/urls.py
from django.urls import re_path
from django.contrib import admin
from . import views
from adclass.views import (
    AdClassView, #main view
    add_tender, add_announce, # add views
    view_tender,
    update_tender,
    delete_tender,
    delete_tender_permanent,
    view_all_tenders,
    filter_tender_type,
    search,
    corp_single_tender_view, corp_single_announce_view, # single objects views
    corp_all_tender_view, corp_all_announce_view, #all objects views
    #FreelancerView,
    #TenderView,

    )

app_name='adclass'

urlpatterns = [
    re_path(r'^all/$', AdClassView.as_view(), name='AdClassView'), #Main view


    #User tenders
    re_path(r'^my_tenders/add/$', views.add_tender, name='add_tender'),
    re_path(r'^tender/update/(?P<slug>[\w-]+)/$', views.update_tender, name='update_tender'),
    re_path(r'^(?P<slug>[-\w]+)/restore_tender/$', views.restore_tender, name='restore_tender'),
    re_path(r'^tenders/$', views.corp_all_tender_view, name='corp_all_tender_view'),
    re_path(r'^tender/(?P<slug>[\w-]+)/$', views.corp_single_tender_view, name='corp_single_tender_view'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', views.delete_tender, name='delete_tender'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', views.delete_tender_permanent, name='delete_tender_permanent'),
    re_path(r'^search/$', views.search, name='search'),

    #announcements
    re_path(r'^announce/add/$', views.add_announce, name='add_announce'),
    #re_path(r'^announce/update/(?P<slug>[\w-]+)/$', views.update_tender, name='update_tender'),
    #re_path(r'^(?P<slug>[-\w]+)/restore_tender/$', views.restore_tender, name='restore_tender'),
    re_path(r'^announce/$', views.corp_all_announce_view, name='corp_all_announce_view'),
    re_path(r'^announce/(?P<slug>[\w-]+)/$', views.corp_single_announce_view, name='corp_single_announce_view'),
    #re_path(r'^(?P<slug>[\w-]+)/delete/$', views.delete_tender, name='delete_tender'),
    #re_path(r'^(?P<slug>[\w-]+)/delete/$', views.delete_tender_permanent, name='delete_tender_permanent'),
    #re_path(r'^search/$', views.search, name='search'),


    #Visitor
    re_path(r'^tender/(?P<slug>[\w-]+)/$', views.view_tender, name='view_tender'),
    re_path(r'^all/$', views.view_all_tenders, name='view_all_tenders'), #visitor
    re_path(r'^filter/<job_type>$', views.filter_tender_type, name='filter_tender_type'),
    ]

basecode/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from basecode import views, settings
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from accounts.admin import admin_site
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', views.login_redirect, name='login_redirect'),
    re_path(r'^account/$', views.login_redirect, name='login_redirect'),
    #path(r'^vimage-admin/', admin.site.urls),#sys dba
    re_path(r'^pervasive-admin/', include('django_sb_admin.urls')),
    #re_path('flock-inc-admin/', admin_site.urls),#management-decision
    #re_path('flock-master-admin/', admin_site.urls),#top level-strategy
    #re_path(r'^account/', include('accounts.urls'),
    re_path(r'^account/', include('accounts.urls', namespace='accounts')),
    re_path(r'^', include('pervasive.urls', namespace='pervasive')),
    re_path(r'^finance/', include('finance.urls', namespace='finance')),
    re_path(r'^flock/', include('flock.urls', namespace='flock')),
    re_path(r'^', include('profiles.urls', namespace='profiles')),
    re_path(r'^blog/', include('blog.urls', namespace='blog')),
    re_path(r'^jobs/', include('jobs.urls', namespace='jobs')),
    re_path(r'^admanager/', include('adclass.urls', namespace='adclass')),
    re_path(r'^products/', include('products.urls', namespace='products')),
    re_path(r'^services/', include('services.urls', namespace='services')),
    re_path(r'^newsletter/', include('newsletter.urls', namespace='newsletter')),
    re_path(r'^recycle/', include('recycle.urls', namespace='recycle')),
    re_path(r'^support/', include('support.urls', namespace='support')),
    re_path(r'^drive/', include('drive.urls', namespace='drive')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    #re_path(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),


    #re_path(r'^utilities/', include('utilities.urls')),
    re_path(r'^about/', include('about.urls', namespace='about')),
    #re_path(r'^pay-pal/', include('pay-pal.urls')),
    #re_path(r'^administration/', include('administration.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

# if settings.DEBUG404:
#     urlpatterns += urlpatterns('',
#         (r'^static/(?P<path>.*)$', staticserve,
#             {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
#         )

handler404 = views.handler404
handler500 = views.handler500

#handler403 = 'mysite.views.my_custom_permission_denied_view'
#handler403 = 'mysite.views.my_custom_permission_denied_view'

#The bad_request() view is overridden by handler400:
#handler400 = 'mysite.views.my_custom_bad_request_view'

blog/urls.py
from django.urls import re_path
from . import views
from blog.views import (
    single_blog,
    view_all_blogs,
    )

app_name='blog'

urlpatterns = [
    re_path(r'^view/(?P<slug>[\w-]+)/$', views.single_blog, name='single_blog'),
    re_path(r'^all/$', views.view_all_blogs, name='view_all_blogs'),
    # re_path(r'^view/(?P<slug>[\w-]+)/news/$', views.single_news, name='single_news'),
    re_path(r'^news/$', views.view_all_news, name='view_all_news'),
    ]

recycle/urls.py
from django.urls import re_path
from . import views
from recycle.views import (
    view_all_deleted, deleted_services, deleted_jobs, deleted_products, deleted_tenders
    )

app_name='recycle'

urlpatterns = [
    #user
    re_path(r'^bin/$', views.view_all_deleted, name='view_all_deleted'),
    re_path(r'^services/$', views.deleted_services, name='deleted_services'),
    re_path(r'^jobs/$', views.deleted_jobs, name='deleted_jobs'),
    re_path(r'^products/$', views.deleted_products, name='deleted_products'),
    re_path(r'^tenders/$', views.deleted_tenders, name='deleted_tenders'),
    ]

adclass/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView
from django.utils import timezone
from django.views.generic import TemplateView, ListView, DetailView
from itertools import chain
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User
from django.urls import reverse
from adclass.forms import TenderForm, TenderApplicantForm, ScholarshipForm, AnnounceForm, EditTenderForm
from . models import TenderApplicant, Tender, Scholarship, Announce
from services.models import Service
from products.models import Product
from jobs.models import PostJob
from django.utils import timezone

def get_ip(request):
    try:
        x_foward = request.META.get("HTTP_X_FOWARDED_FOR")
        if x_foward:
            ip = x_foward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = '127.0.0.1'
    return ip

'''For Clients(User)'''
class AdClassView(TemplateView):
    template_name                   = 'profiles/adclass/main_view.html'
    def get(self, request, user =None):
        services                    = Service.objects.filter(user=request.user).filter(active=True).filter(deleted=False).all()
        products                    = Product.objects.filter(user=request.user).filter(active=True).filter(deleted=False).all()
        tenders                     = Tender.objects.filter(user=request.user).filter(active=True).filter(deleted=False).all()
        jobs                        = PostJob.objects.filter(user=request.user).filter(active=True).filter(deleted=False).all()
        announce                    = Announce.objects.filter(user=request.user).filter(active=True).filter(deleted=False).all()
        t_services                  = services.count()
        t_products                  = products.count()
        t_tenders                   = tenders.count()
        t_jobs                      = jobs.count()
        t_announce                  = announce.count()
        total                       = t_services + t_products + t_tenders + t_jobs + t_announce
        context = {
            "title"                 : 'ads | manager',
            'services'              : services,
            'products'              : products,
            'tenders'               : tenders,
            'jobs'                  : jobs,
            'announce'              : announce,
            'total'                 : total,
        }
        return render(request, self.template_name, context)

@login_required
def add_tender(request):
    template_name = 'profiles/adclass/tender/add_tender.html'
    form = TenderForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        tender = form.save(commit=False)
        tender.user = request.user
        tender.save()
        return redirect('adclass:AdClassView')
    else:
        form = TenderForm(request.POST or None, request.FILES or None)
    #print(form.errors)
    context = {
        'tiltte': 'Tender | add',
        'form': form,
    }
    return render(request, template_name, context)

@login_required
def corp_all_tender_view(request):
    tenders                 = Tender.objects.filter(user=request.user).order_by('-created')
    template_name       = 'profiles/adclass/tender/all_tenders.html'
    context             = {
        'tittle': 'Tenders | all',
        'tenders': tenders,
    }
    return render(request, template_name, context)

@login_required
def corp_single_tender_view(request, slug=None):
    tender                 = get_object_or_404(Tender, slug=slug)
    template_name = 'profiles/adclass/tender/single_tender.html'
    context = {
        'title': 'Tender | All',
        'tender': tender,
    }
    return render(request, template_name, context)

@login_required
def update_tender(request, slug=None):
    tender = get_object_or_404(Tender, slug=slug)
    template_name = 'profiles/adclass/tender/update_tender.html'
    form = EditTenderForm(request.POST or None, request.FILES or None, instance=tender)
    if form.is_valid():
        tender          = form.save(commit=False)
        tender.edited   = True
        tender.updated  = timezone.now()
        tender.save()
        return redirect(reverse('adclass:corp_single_tender_view', kwargs={'slug': tender.slug}))
    else:
        form = EditTenderForm(request.POST or None, request.FILES or None, instance=tender)
        #messages.success(request, 'Your password was updated successfully!')
    context = {
        'title': 'Tender | update',
        "tender": tender,
        "form":form,
    }
    return render(request, template_name, context)

@login_required
def delete_tender(request, slug=None):
    tender             = get_object_or_404(Tender, slug=slug)
    tender.deleted     = True
    tender.active      = False
    tender.save()
    return redirect("adclass:AdClassView")

@login_required
def restore_tender(request, slug=None):
    tender             = get_object_or_404(Tender, slug=slug)
    tender.deleted     = False
    tender.active      = True
    tender.save()
    return redirect("adclass:AdClassView")

@login_required
def delete_tender_permanent(request, slug=None):
    tender = get_object_or_404(Tender, slug=slug)
    tender.delete()
    tender.save()
    return redirect("adclass:AdClassView")


'''
ANNOUNCEMTNTS
'''
@login_required
def add_announce(request):
    template_name = 'profiles/adclass/general/add_announce.html'
    form = AnnounceForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        announce = form.save(commit=False)
        announce.user = request.user
        announce.save()
        return redirect('adclass:AdClassView')
    else:
        form = AnnounceForm(request.POST or None, request.FILES or None)
    #print(form.errors)
    context = {
        'tittle': 'Announcements | add',
        'form': form,
    }

    return render(request, template_name, context)

@login_required
def corp_all_announce_view(request):
    announce                 = Announce.objects.filter(user=request.user).order_by('-created')
    template_name       = 'profiles/adclass/general/all_announcements.html'
    context             = {
        'title': 'Announcements | all',
        'announce': announce,
    }
    return render(request, template_name, context)

@login_required
def corp_single_announce_view(request, slug=None):
    announce                 = get_object_or_404(Announce, slug=slug)
    template_name = 'profiles/adclass/general/single_announce_corp.html'
    context = {
        'title': 'Announcement',
        'announce': announce,
    }
    return render(request, template_name, context)

@login_required
def delete_announce(request, slug=None):
    announce             = get_object_or_404(Announce, slug=slug)
    announce.deleted     = True
    announce.active      = False
    announce.save()
    return redirect("adclass:AdClassView")

@login_required
def restore_tender(request, slug=None):
    announce             = get_object_or_404(Announce, slug=slug)
    announce.deleted     = False
    announce.active      = True
    announce.save()
    return redirect("adclass:AdClassView")

@login_required
def delete_tender_permanent(request, slug=None):
    announce = get_object_or_404(Announce, slug=slug)
    announce.delete()
    announce.save()
    return redirect("adclass:AdClassView")





#Visitor
def view_all_tenders(request):
    tenders = list()
    try:
        tenders               = Tender.objects.filter(active=True).filter(deleted=False).all()
    except: pass

    paginator = Paginator(tenders, 2) # Show 25 jobs per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        tenders = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        tenders = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        tenders = paginator.page(paginator.num_pages)
    #template_name
    context = {
        'tenders': tenders,
    }
    return render(request, 'adclass/all_tenders.html', {'tenders': tenders,})


def view_tender(request, slug=None):
    template_name = 'pervasive/adclass/tender/single_tender.html'
    tender = list()
    try:
        tender               = get_object_or_404(Tender, slug=slug)
        ''''
        Record the last accessed date and number of view
        model manager function with ip address META PARAM option
        '''
        view_by           = get_ip(request)
        qs                = tender.objects.get(view_by__iexact=view_by).exist()
        if not qs:
            '''increament tender views by one(Only if the user has not viewed before)'''
            tender.update(views=F('views')+1)
            tender.view_by = get_ip(request)
            tender.save()
        else: pass
        tender.views = views + 1
        #tender.last_accessed = timezone.now()
        tender.save()
    except: pass
    context = {
        'tender': tender,
    }
    return render(request, template_name, context)

def filter_tender_type(request, tender_type=None):
    tender = list()
    try:
        tender               = Tender.objects.filter(tender_type=tender_type)
    except:
        pass
    template_name = 'profiles/adclass/tenders/tender_filter.html'
    context = {
        'tittle': tender.tender_type,
        'tender': tender,
    }
    return render(request, template_name, context)

@require_http_methods(['GET'])
def search(request):
    query                               = request.GET.get('q')

templates/profiles/adclass/tender/add_tender.html
{% extends 'profiles/index/profile_index.html' %}

{% block content %}

<div class="card-header">
  <div class="col-sm-6 text-left">
    <h5 class="card-category">Tenders</h5>
    <h4 class="card-title">Add new {{ user }} tender here</h4>
  </div>
</div>
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="dropdown float-right">
          <button type="button" class="btn btn-link dropdown-toggle btn-icon" data-toggle="dropdown" aria-expanded="false">
            <i class="tim-icons icon-settings-gear-63"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink" x-placement="bottom-end" style="position: absolute; transform: translate3d(-122px, 22px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" href="{% url 'adclass:add_tender' %}">New</a>
            <a class="dropdown-item" href="">Top viewed</a>
            <a class="dropdown-item" href="#pablo">Most applied</a>
            <a class="dropdown-item" href="#pablo">Old</a>
            <a class="dropdown-item" href="{% url 'recycle:deleted_tenders' %}">deleted</a>
          </div>
        </div>
        <br>
            <form class="" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token  %}
                {% if form.errors %}
                {{ form.non_field_errors }}
                <!-- Tender Video -->
                <div class="alert">
                  <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                  </button>
                  <ul style="list-style:none;">
                    <li class="alert-danger"> <b> Warning - </b> {{ form.errors }} </li>
                  </ul>

                </div>
                {% endif %}
                {{ form.media }}
              <div class="card-body">
                  <div class="row">

                    <div class="col-md-12 pr-md-1">
                      <label for="upload-video" class="" style="cursor: pointer;">
                          <i class="tim-icons icon-upload btn-sm"> upload</i>
                      </label>
                      <i name="job_video-clear" id="tender_video-clear_id" class="tim-icons icon-trash-simple btn-sm float-right" style="cursor: pointer;"> clear</i>
                      <input type="file" name="tender_video" id="upload-video" style="display:none;" accept="video/*" onchange="loadFile(event)">
                      <video id="output" data-play="hover" width="100%" height="auto" src="{{ tender.tender_video.url }}" type="video/*"
                        preload loop subtitles srclang="en" controls controlsList="nodownload" poster="">
                      </video>
                      <!-- Tender tittle -->
                        <div class="form-group">
                          <div class="fieldWrapper">
                            {{ form.tender_tittle.error }}
                            <label for="{{ form.tender_tittle.id_for_label }}">Tender Name</label>
                              {{ form.tender_tittle }}
                          </div>
                        </div>
                    </div>
                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <div class="fieldWrapper">
                          <label for="{{ form.content.id_for_label }}">Content </label>
                          {{ form.content.error }}
                          {{ form.content }}
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 px-md-1">
                      <div class="form-group">
                        <div class="field-city">
                          <div>
                            <label class="required" for="{{ form.city.id_for_label }}">City:</label>
                                {{ form.city }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 px-md-1">
                      <div class="form-group">
                        <div class="field-address">
                          <div>
                            <label class="required" for="{{ form.address.id_for_label }}">address:</label>
                                {{ form.address }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 px-md-1">
                      <div class="form-group">
                        <div>
                          <label class="required" for="{{ form.levy_price.id_for_label }}">Levy:</label>
                            {{ form.levy_price.error }}
                            {{ form.levy_price }}
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 px-md-1">
                      <div class="form-group">
                        <div class="datepicker-container">
                          <label for="{{ form.due_date.id_for_label }}">Due date </label>
                          {{ form.due_date.error }}
                          {{ form.due_date }}
                        </div>
                          <script type="text/javascript">
                              $(function () {
                                  $('#datepicker').datepicker({
                                      daysOfWeekDisabled: [0, 6]
                                  });
                              });
                          </script>
                      </div>
                    </div>
                    <h4 class="col-md-12 pr-md-1">Contacts</h4>
                    <div class="col-md-6 pr-md-1">
                      <div class="form-group">
                        {{ form.contact_person_name.error }}
                        <label for="{{ form.contact_person_name.id_for_label }}">Contact Person Office name</label>
                        {{ form.contact_person_name }}
                      </div>
                    </div>
                    <div class="col-md-6 px-md-1">
                      <div class="form-group">
                        {{ form.office_no.error }}
                        <label for="{{ form.office_no.id_for_label }}">Office number</label>
                        {{ form.office_no }}
                      </div>
                    </div>
                  </div>

              </div>
              <div class="modal-footer">
                  <button type="button" class="float-left btn btn-primary btn-sm btn-raised btn-round" data-dismiss="modal">Cancel</button>
                  <button type="submit" name="submit" class="btn btn-primary btn-sm btn-raised btn-round" onclick="demo.showNotification('top','center')">Save</button>
              </div>
            </form>
            <!-- END ALL FORM -->
          <div class="card-footer text-right">
            <button type="submit" class="btn btn-fill btn-sm btn-round btn-primary">load more...</button>
          </div>
          <div class="content-center">
            <div class="card-description">
              <h2 class="description">About Basecode GTI tenders </h2>
            </div>
          </div>
        <!-- END MAIN PAGE TENDERS -->
      </div>
    </div>
</div>
<script type="text/javascript">
  var loadFile = function(event) {
    var reader = new FileReader();
    reader.onload = function(){
      var output = document.getElementById('output');
      if (output.src == ''){
        this.style.display = "none";
      }
      output.src = reader.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  };
</script>
{% endblock %}

templates/profiles/adclass/tender/all_tenders.html
{% extends 'profiles/index/profile_index.html' %}

{% block content %}

<div class="container">
<h5 class="card-category text-right">
  {% with total=tenders.count %} {{ total }} Tender{{ total|pluralize }} {% endwith %}
</h5>
  <div class="col-sm-12">
    <h3 class=" text-center text-muted">All of {{ user }}'s tenders</h3>
  </div>
</div>
    <div class="row">
      <div class="col-md-12">
        <div class="dropdown float-right">
          <button type="button" class="btn btn-link dropdown-toggle btn-icon" data-toggle="dropdown" aria-expanded="false">
            <i class="tim-icons icon-settings-gear-63"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink" x-placement="bottom-end" style="position: absolute; transform: translate3d(-122px, 22px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" href="{% url 'adclass:add_tender' %}">New</a>
            <a class="dropdown-item" href="">Top viewed</a>
            <a class="dropdown-item" href="#pablo">Most applied</a>
            <a class="dropdown-item" href="#pablo">Old</a>
            <a class="dropdown-item" href="{% url 'recycle:deleted_tenders' %}">deleted</a>
          </div>
        </div>
        <br>
        <hr>
            {% for tender in tenders %}
                    <div class="content container">
                      <h4 class="text-muted card-title d-inline">
                        {{ tender.id }}. <a href="{% url 'adclass:view_tender' slug=tender.slug %}">{{ tender.tender_tittle|capfirst }}</a>
                        <span class="description">{% if tender.edited %}| edited on {{ tender.updated }} {% endif %} </span>
                        <span class="float-right btn-link btn-primary btn-sm" rel="tooltip" title="" data-original-title="Delete {{ tender.tender_tittle|capfirst }}"><a href="#" data-toggle="modal" data-target="#delete-tender-modal"><i class="tim-icons icon-trash-simple"></i></a> </span>
                        {% include 'profiles/adclass/tender/delete_tender_modal.html' %}
                        <span class="float-right text-right btn-link btn-primary btn-sm" rel="tooltip" title="" data-original-title="Edit {{ tender.tender_tittle|capfirst }}"> <a href="{% url 'adclass:update_tender' slug=tender.slug %}" ><i class="tim-icons icon-pencil"></i></a> </span>
                      </h4>
                      <div class="social-description ">
                        <h4 class="card-category text-muted"><i class="tim-icons icon-tap-02 text-primary"></i><span class="badge">{{ tender.views }} views</span> <i class="tim-icons icon-square-pin text-primary"></i><span class="badge">3 applicants</span> <span class="description">{{ tender.created }}</span></h4>
                      </div>
                    </div>
            {% empty %}
            <div class="content-center container">
              <div class="card-description text-center">
                <h4 class="card-category"><i class="tim-icons icon-tap-02 text-primary"></i><span class="badge">Your Have no active Tenders right now. use <a href="{% url 'adclass:add_tender' %}">this form</a> to add</span> <i class="tim-icons icon-square-pin text-primary"></i><span class="badge">3 flock</span> </h4>
              </div>
            </div>
            {% endfor %}
          <div class="content-center container">
            <div class="card-description">
              <h5 class="description">About tenders </h5>
            </div>
          </div>
        <!-- END MAIN PAGE JOBS -->
      </div>
    </div>


{% endblock %}

templates/profiles/adclass/tender/delete_tender_modal.html
<div class="modal fade modal-mini modal-neutral show" id="delete-tender-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: ;">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header justify-content-center">
              <div class="modal-profile">
                  <i class="now-ui-icons users_circle-08"></i>
              </div>
          </div>
          <div class="modal-body">
              <p style="text-align:center;" class="justify-content-center">
                Are you sure you want to delete this tender?
                Note: All deleted tenders are moved to the <a href="#"><i class="tim-icons icon-trash-simple"></i> bin</a> folder.
              </p>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-sm bt-round btn-primary" data-dismiss="modal">Cancel</button>
              <span  class="float-right btn btn-link btn-neutral"> <a href="{% url 'adclass:delete_tender' slug=tender.slug %}">delete</a> </span>
          </div>
      </div>
  </div>
</div>

templates/profiles/adclass/tender/read_full_tender_modal.html
<div class="modal fade modal-mini modal-neutral show" id="read-full-service-modal" tabindex="-1" role="dialog" aria-labelledby="fullservice" style="display: ;width:100%;height:auto;">
  <div class="modal-dialog">
      <div class="modal-content card">
          <div class="modal-body">
              <p style="text-align:center;" class="justify-content-center">
                <div class="content">
                        {{ service.content|safe|urlizetrunc:15 }}
                </div>
                <div class="footer">
                  <div class="modal-footer">
                      <button type="button" class="btn btn-sm btn-round btn-primary" data-dismiss="modal">cancel</button>
                      <!-- <button type="button" class="btn btn-sm btn-round btn-primary" data-dismiss="modal">apply</button> -->
                  </div>

                </div>

          </div>

      </div>
  </div>
</div>

templates/profiles/adclass/tender/share_tender.html
<div class="button-container container">
  <h3>
  <div class="float-right">
    Share
    <button href="javascript:void(0)" class="btn btn-icon btn-round btn-facebook">
      <i class="fab fa-facebook"></i>
    </button>
    <button href="javascript:void(0)" class="btn btn-icon btn-round btn-twitter">
      <i class="fab fa-twitter"></i>
    </button>
    <button href="javascript:void(0)" class="btn btn-icon btn-round btn-google">
      <i class="fab fa-google-plus"></i>
    </button>
  </div>
  </h3>
</div>

templates/profiles/adclass/tender/single_tender.html
{% extends 'profiles/index/profile_index.html' %}


{% block content %}
<div class="card-body">
  <br>
  <div class="row">
    <div class="col-md-12">
      <!-- ALL tenders client VIEW -->
      <span class="current text-center">
        <h4 class=" text text-muted"> {{ tender.tender_tittle }} | {{ tender.created|timesince }} ago</h4>
      </span>
      
      <br>
        {% include 'profiles/adclass/tender/rotate_tender.html' %}
          <div class="card-description">
          {% include 'profiles/adclass/tender/tender_requests.html' %}
          {% include 'profiles/adclass/tender/share_tender.html' %}
        </div>
        <br>
              <!-- BOTTOM PAGINATION -->
              <!--  include 'tenders/pagination.html' -->
            <!-- END BOTTOM PAGINATION -->
          <!-- END ALL tenders VIEW -->

        <div class="content-center container">
          <div class="card-description">
            <br><br>
            <h4 class="description text-muted">About Tenders</h4>
          </div>
        </div>
      <!-- END MAIN PAGE tenders -->
    </div>
  </div>
</div>
{% endblock %}