about/urls.py
from django.urls import re_path
from . views import plans, testimonies, our_team, faqs, upgrade

app_name='about'

urlpatterns = [
    re_path(r'^plans/$', plans, name='plans'),
    re_path(r'^plans/upgrade/$', upgrade, name='upgrade'),



    re_path(r'^faq\'s/$', faqs, name='faqs'),
    # re_path(r'^request-a-demo/$', faqs, name='request_a_demo'),
]

accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    re_path(r'^login/$', auth_views.LoginView.as_view(), {'template_name': 'registration/index.html'}, name='login'),
    re_path(r'^$', views.logout, {'template_name': 'pervasive/index.html'}, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile'),
    re_path(r'^edit/$', views.edit_profile, name='edit_profile'),
    re_path(r'^update/$', views.edit_view, name='edit_view'),
    re_path(r'^edit/display/$', views.edit_display, name='edit_display'),
    re_path(r'^edit/contacts/$', views.edit_contacts, name='edit_contacts'),
    re_path(r'^edit/media/$', views.edit_media, name='edit_media'),
    re_path(r'^edit/profile_image/$', views.edit_profile_image, name='edit_profile_image'),
    re_path(r'^edit/profile_cover/$', views.edit_cover_image, name='edit_cover_image'),
    re_path(r'^change-password/$', views.change_password, name='change_password'),
    re_path(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name=
        'registration/reset_password.html' ), {'post_reset_redirect':
            'accounts:password_reset_done', 'email_template_name':
                'registration/reset_password_email.html'}, name='reset_password'),
    re_path(r'^reset-password/done/$', auth_views.PasswordResetDoneView.as_view(template_name=
        'registration/password_reset_done.html'), {},
        name='password_reset_done'),
    re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(), {'post_reset_redirect': 'registration/password_reset_complete'},
        name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),
]

basecode/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from basecode import views, settings
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from accounts.admin import admin_site
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', views.login_redirect, name='login_redirect'),
    re_path(r'^account/$', views.login_redirect, name='login_redirect'),
    #path(r'^vimage-admin/', admin.site.urls),#sys dba
    re_path(r'^pervasive-admin/', include('django_sb_admin.urls')),
    #re_path('flock-inc-admin/', admin_site.urls),#management-decision
    #re_path('flock-master-admin/', admin_site.urls),#top level-strategy
    #re_path(r'^account/', include('accounts.urls'),
    re_path(r'^account/', include('accounts.urls', namespace='accounts')),
    re_path(r'^', include('pervasive.urls', namespace='pervasive')),
    re_path(r'^finance/', include('finance.urls', namespace='finance')),
    re_path(r'^flock/', include('flock.urls', namespace='flock')),
    re_path(r'^', include('profiles.urls', namespace='profiles')),
    re_path(r'^blog/', include('blog.urls', namespace='blog')),
    re_path(r'^jobs/', include('jobs.urls', namespace='jobs')),
    re_path(r'^admanager/', include('adclass.urls', namespace='adclass')),
    re_path(r'^products/', include('products.urls', namespace='products')),
    re_path(r'^services/', include('services.urls', namespace='services')),
    re_path(r'^newsletter/', include('newsletter.urls', namespace='newsletter')),
    re_path(r'^recycle/', include('recycle.urls', namespace='recycle')),
    re_path(r'^support/', include('support.urls', namespace='support')),
    re_path(r'^drive/', include('drive.urls', namespace='drive')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    #re_path(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),


    #re_path(r'^utilities/', include('utilities.urls')),
    re_path(r'^about/', include('about.urls', namespace='about')),
    #re_path(r'^pay-pal/', include('pay-pal.urls')),
    #re_path(r'^administration/', include('administration.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

# if settings.DEBUG404:
#     urlpatterns += urlpatterns('',
#         (r'^static/(?P<path>.*)$', staticserve,
#             {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
#         )

handler404 = views.handler404
handler500 = views.handler500

#handler403 = 'mysite.views.my_custom_permission_denied_view'
#handler403 = 'mysite.views.my_custom_permission_denied_view'

#The bad_request() view is overridden by handler400:
#handler400 = 'mysite.views.my_custom_bad_request_view'

blog/urls.py
from django.urls import re_path
from . import views
from blog.views import (
    single_blog,
    view_all_blogs,
    )

app_name='blog'

urlpatterns = [
    re_path(r'^view/(?P<slug>[\w-]+)/$', views.single_blog, name='single_blog'),
    re_path(r'^all/$', views.view_all_blogs, name='view_all_blogs'),
    # re_path(r'^view/(?P<slug>[\w-]+)/news/$', views.single_news, name='single_news'),
    re_path(r'^news/$', views.view_all_news, name='view_all_news'),
    ]

jobs/urls.py
from django.urls import re_path
from . import views
from jobs.views import (
    JobView, add_job, view_job, update_job, delete_job,
    view_all_jobs, filter_job_type, search, corp_single_job_view,
    corp_all_job_view, restore_job, remote_jobs
    #FreelancerView,
    #TenderView,

    )

app_name='jobs'

urlpatterns = [
    #user

    re_path(r'^my-jobs/$', JobView.as_view(), name='JobView'),
    re_path(r'^add/$', views.add_job, name='add_job'),
    re_path(r'^(?P<slug>[\w-]+)/update/$', views.update_job, name='update_job'),
    re_path(r'^(?P<slug>[-\w]+)/delete/$', views.delete_job, name='delete_job'),
    re_path(r'^(?P<slug>[-\w]+)/restore_job/$', views.restore_job, name='restore_job'),
    re_path(r'^(?P<slug>[\w-]+)/view/$', views.corp_single_job_view, name='corp_single_job_view'),
    #url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_job_permanent, name='delete_job_permanent'),




    re_path(r'^all$', views.view_all_jobs, name='view_all_jobs'), #visitor
    re_path(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.view_job, name='view_job'),
    #re_path(r'^all/view/$', views.corp_all_job_view, name='corp_all_job_view'), ##visitor
    re_path(r'^remote-jobs/$', views.remote_jobs, name='remote_jobs'),

    re_path(r'^filter/<job_type>$', views.filter_job_type, name='filter_job_type'),
    re_path(r'^search/$', views.search, name='search'),
    ]

pervasive/urls.py
from django.urls import re_path
from . views import pervasive_view, product_n_services, validate_email
from profiles.views import single_post

app_name='pervasive'


urlpatterns = [
    re_path(r'^$', pervasive_view, name='pervasive_view'),
    re_path(r'^validate_email/$', validate_email, name='validate_email'),
    re_path(r'^blog/(?P<slug>[\w-]+)/$', single_post, name='single_post'), 
    re_path(r'^product-n-services/$', product_n_services, name='product_n_services'),
    # re_path(r'^pervasive/$', trending, name='trending_view'),
    # re_path(r'^pervasive/$', jobs, name='jobs_view'),
    # re_path(r'^pervasive/$', tender, name='tender_view'),
    # re_path(r'^pervasive/$', scholarship, name='trending_view'),
    # re_path(r'^pervasive/$', blogs, name='blogs_view'),


]

pervasive/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

pervasive/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.models import User
from finance.models import UserMembership, Membership
from profiles.models import Profile
from flock.models import Friend, Post, Comments
from jobs.models import PostJob
from products.models import Product
from services.models import Service
from adclass.models import Tender
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from newsletter.forms import JoinForm
from datetime import datetime
from itertools import chain
import json
from django.shortcuts import *
from django.template import RequestContext

                ###############################
                ###PERVASIVE HOME PAGE VIEW###
                ###############################

'''
Get the users ip address as the page loads to inrease relativity.
By means of viewing profiles by near location
'''
def get_ip(request):
    try:
        x_foward = request.META.get("HTTP_X_FOWARDED_FOR")
        if x_foward:
            ip = x_foward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ''

    return ip

def near_by_loc(request):
    pass

'''
Page loads
'''
def pervasive_view(request):
    visitor_location    = get_ip(request)
    #visits = VsitForm(request.POST or None)
    #relate = User.BusinessBaseProfile.near_by('user_location').all().order_by('ip_address')
    profile                     = Profile.objects.filter(active=True).all()


    '''
    basecode newsletter subscription form
    '''
    # join_form = JoinForm(request.POST or None)
    # if request.method == 'POST':
    #     email = request.POST.get('email')
    #     response_data = {}
    #     #join_form = JoinForm(email = email)
    #     join_form.save(commit=False)
    #     join_form.ip_address = get_ip(request)
    #     join_form.save()
    #
    #     response_data['result'] = 'Success!!.'
    #
    #     return HttpResponse(
    #         json.dumps({response_data}),
    #         content_type="application/json"
    #     )
    # else:
    #     return HttpResponse(
    #         json.dumps({"nothing to see": "this isn't happening"}),
    #         content_type="application/json"
    #     )
    join_form = JoinForm(request.POST or None)
    if join_form.is_valid():
        join_form.save(commit=False)
        join_form.ip_address = get_ip(request)
        join_form.save()
        return redirect(reverse('pervasive:HomeView'))
    ''''''
    tittle = 'Pervasive | home'
    context = {
        'tittle'        : tittle,
        'join_form'     : join_form,
        'profile'       : profile,
    }
    return render(request, 'pervasive/home/home.html', context)

def product_n_services(request):
    template_name = 'pervasive/ps/product_n_services.html'
    products_results                = Product.objects.all()
    services_results                = Service.objects.all()
    tenders_results                 = Tender.objects.all()

    queryset_chain              = chain(
            products_results,
            services_results,
            tenders_results
    )
    qs                           = sorted(queryset_chain,
        key                     = lambda instance: instance.created or instance.created,
        reverse                 = True
        )
    #qs.count                  = len(qs)
    context={
        'object_list': qs,
    }
    return render(request, template_name, context)

def validate_email(request):
    email = request.GET.get('email', None)
    data = {
        'is_taken': JoinForm.objects.filter(email__iexact=email__iexact).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

templates/pervasive/nav/header_nav.html
<!-- Navbar -->
<nav class="navbar navbar-color-on-scroll fixed-top navbar-expand-lg navbar navbar-inverse navbar-expand-lg bg-rose" color-on-scroll="100" id="sectionsNav">
  <div class="container">
    <div class="navbar-translate">
      <a class="navbar-brand" href="/">
        Basecode GTI </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    
    <div class="collapse navbar-collapse">

      <ul class="navbar-nav ml-auto">

        <li class="nav-item">
          <form class="form-inline ml-auto" action="{% url 'flock:search' %}" method="GET">
            <div class="form-group has-white bmd-form-group">
              <input type="text"  name="q" class="form-control" value="{{ request.GET.q }}" placeholder="Search">
            </div>
            <button type="submit" name="submit" class="btn btn-white btn-raised btn-sm btn-fab btn-round">
              <i class="material-icons">search</i>
            </button>
          </form>
        </li>
        <li class="dropdown nav-item">
          <a href="#" class="nav-link disabled" data-toggle="dropdown">
            Teams
          </a>
          <div class="dropdown-menu dropdown-with-icons">
            <a href="../index.html" class="dropdown-item">
              Trending
              </a>
            <a href="" class="dropdown-item">
              Popular
            </a>
            <a href="" class="dropdown-item">
              Add your team
            </a>
          </div>
        </li>
        <li class="dropdown nav-item">
          <a href="#" class="nav-link" data-toggle="dropdown">
            Videos
          </a>
          <div class="dropdown-menu dropdown-with-icons">
            <!-- <a href="../index.html" class="dropdown-item">
              Trending
            </a> -->
            <a href="{% url 'pervasive:product_n_services' %}" class="dropdown-item">
              PS
            </a>
            <!-- <a href="#" class="dropdown-item">
              Popular
            </a> -->
          </div>
        </li>
        <li class="dropdown nav-item">
          <a href="#" class="nav-link" data-toggle="dropdown">
            Jobs
          </a>
          <div class="dropdown-menu dropdown-with-icons">
            <a href="{% url 'jobs:view_all_jobs' %}" class="dropdown-item">
              All
            </a>
            <a href="{% url 'jobs:remote_jobs' %}" class="dropdown-item">
              Remote
            </a>
            <!-- <a href="{% url 'jobs:remote_jobs' %}" class="dropdown-item">
              Teams hiring
            </a> -->
            <!-- <a href="#" class="dropdown-item">
              Others (re-advatised)
            </a> -->
          </div>
        </li>
        <li class="nav-item">

        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'about:plans' %}" onclick="scrollToDownload()">
            Pricing
          </a>
        </li>
        <li class="dropdown nav-item">
          <a href="#" class="nav-link" data-toggle="dropdown">
            Company
          </a>
          <div class="dropdown-menu dropdown-with-icons">
            <a href="{% url 'blog:view_all_blogs' %}" class="dropdown-item">
              Blog
            </a>
            <a href="{% url 'blog:view_all_news' %}" class="dropdown-item">
              News
            </a>
            <a href="{% url 'about:faqs' %}" class="dropdown-item">
              About
            </a>
            <!-- <a href="#" class="dropdown-item">
              Case Studies
            </a>
            <a href="#" class="dropdown-item">
              Shops
            </a> -->
            <a href="#" class="dropdown-item">
              Careers (coming soon)
            </a>
            <!-- <a href="#" class="dropdown-item">
              Adverts
            </a> -->
            <a href="#" class="dropdown-item">
              Advitise
            </a>
            <a href="#" class="dropdown-item">
              API's (coming soon)
            </a>
            <a href="{% url 'about:faqs' %}" class="dropdown-item">
              FAQ's
            </a>
            <!-- <a href="#" class="dropdown-item">
              Apps
            </a> -->
            <a href="{% url 'about:plans' %}#contact" class="dropdown-item">
              Help
            </a>
          </div>
        </li>

        <!-- <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="#" target="_blank" data-original-title="Follow us on Twitter">
            <i class="fa fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="#" target="_blank" data-original-title="Like us on Facebook">
            <i class="fa fa-facebook-square"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="#" target="_blank" data-original-title="Follow us on Instagram">
            <i class="fa fa-instagram"></i>
          </a>
        </li> -->
        <li class="button-container nav-item iframe-extern">
            <a href="{% url 'accounts:login' %}" data-original-title="Pervasive Account" class="btn  btn-info btn-sm  btn-round btn-block">
              Login<i class="material-icons">fingerprint</i>
            <div class="ripple-container"></div></a>
          </li>
      </ul>
    </div>
  </div>
</nav>

<!-- End Navbar -->