about/urls.py
from django.urls import re_path
from . views import plans, testimonies, our_team, faqs, upgrade

app_name='about'

urlpatterns = [
    re_path(r'^plans/$', plans, name='plans'),
    re_path(r'^plans/upgrade/$', upgrade, name='upgrade'),



    re_path(r'^faq\'s/$', faqs, name='faqs'),
    # re_path(r'^request-a-demo/$', faqs, name='request_a_demo'),
]

basecode/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from basecode import views, settings
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from accounts.admin import admin_site
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', views.login_redirect, name='login_redirect'),
    re_path(r'^account/$', views.login_redirect, name='login_redirect'),
    #path(r'^vimage-admin/', admin.site.urls),#sys dba
    re_path(r'^pervasive-admin/', include('django_sb_admin.urls')),
    #re_path('flock-inc-admin/', admin_site.urls),#management-decision
    #re_path('flock-master-admin/', admin_site.urls),#top level-strategy
    #re_path(r'^account/', include('accounts.urls'),
    re_path(r'^account/', include('accounts.urls', namespace='accounts')),
    re_path(r'^', include('pervasive.urls', namespace='pervasive')),
    re_path(r'^finance/', include('finance.urls', namespace='finance')),
    re_path(r'^flock/', include('flock.urls', namespace='flock')),
    re_path(r'^', include('profiles.urls', namespace='profiles')),
    re_path(r'^blog/', include('blog.urls', namespace='blog')),
    re_path(r'^jobs/', include('jobs.urls', namespace='jobs')),
    re_path(r'^admanager/', include('adclass.urls', namespace='adclass')),
    re_path(r'^products/', include('products.urls', namespace='products')),
    re_path(r'^services/', include('services.urls', namespace='services')),
    re_path(r'^newsletter/', include('newsletter.urls', namespace='newsletter')),
    re_path(r'^recycle/', include('recycle.urls', namespace='recycle')),
    re_path(r'^support/', include('support.urls', namespace='support')),
    re_path(r'^drive/', include('drive.urls', namespace='drive')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    #re_path(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),


    #re_path(r'^utilities/', include('utilities.urls')),
    re_path(r'^about/', include('about.urls', namespace='about')),
    #re_path(r'^pay-pal/', include('pay-pal.urls')),
    #re_path(r'^administration/', include('administration.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

# if settings.DEBUG404:
#     urlpatterns += urlpatterns('',
#         (r'^static/(?P<path>.*)$', staticserve,
#             {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
#         )

handler404 = views.handler404
handler500 = views.handler500

#handler403 = 'mysite.views.my_custom_permission_denied_view'
#handler403 = 'mysite.views.my_custom_permission_denied_view'

#The bad_request() view is overridden by handler400:
#handler400 = 'mysite.views.my_custom_bad_request_view'

blog/urls.py
from django.urls import re_path
from . import views
from blog.views import (
    single_blog,
    view_all_blogs,
    )

app_name='blog'

urlpatterns = [
    re_path(r'^view/(?P<slug>[\w-]+)/$', views.single_blog, name='single_blog'),
    re_path(r'^all/$', views.view_all_blogs, name='view_all_blogs'),
    # re_path(r'^view/(?P<slug>[\w-]+)/news/$', views.single_news, name='single_news'),
    re_path(r'^news/$', views.view_all_news, name='view_all_news'),
    ]

pervasive/urls.py
from django.urls import re_path
from . views import pervasive_view, product_n_services, validate_email
from profiles.views import single_post

app_name='pervasive'


urlpatterns = [
    re_path(r'^$', pervasive_view, name='pervasive_view'),
    re_path(r'^validate_email/$', validate_email, name='validate_email'),
    re_path(r'^blog/(?P<slug>[\w-]+)/$', single_post, name='single_post'), 
    re_path(r'^product-n-services/$', product_n_services, name='product_n_services'),
    # re_path(r'^pervasive/$', trending, name='trending_view'),
    # re_path(r'^pervasive/$', jobs, name='jobs_view'),
    # re_path(r'^pervasive/$', tender, name='tender_view'),
    # re_path(r'^pervasive/$', scholarship, name='trending_view'),
    # re_path(r'^pervasive/$', blogs, name='blogs_view'),


]

pervasive/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

pervasive/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.models import User
from finance.models import UserMembership, Membership
from profiles.models import Profile
from flock.models import Friend, Post, Comments
from jobs.models import PostJob
from products.models import Product
from services.models import Service
from adclass.models import Tender
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from newsletter.forms import JoinForm
from datetime import datetime
from itertools import chain
import json
from django.shortcuts import *
from django.template import RequestContext

                ###############################
                ###PERVASIVE HOME PAGE VIEW###
                ###############################

'''
Get the users ip address as the page loads to inrease relativity.
By means of viewing profiles by near location
'''
def get_ip(request):
    try:
        x_foward = request.META.get("HTTP_X_FOWARDED_FOR")
        if x_foward:
            ip = x_foward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ''

    return ip

def near_by_loc(request):
    pass

'''
Page loads
'''
def pervasive_view(request):
    visitor_location    = get_ip(request)
    #visits = VsitForm(request.POST or None)
    #relate = User.BusinessBaseProfile.near_by('user_location').all().order_by('ip_address')
    profile                     = Profile.objects.filter(active=True).all()


    '''
    basecode newsletter subscription form
    '''
    # join_form = JoinForm(request.POST or None)
    # if request.method == 'POST':
    #     email = request.POST.get('email')
    #     response_data = {}
    #     #join_form = JoinForm(email = email)
    #     join_form.save(commit=False)
    #     join_form.ip_address = get_ip(request)
    #     join_form.save()
    #
    #     response_data['result'] = 'Success!!.'
    #
    #     return HttpResponse(
    #         json.dumps({response_data}),
    #         content_type="application/json"
    #     )
    # else:
    #     return HttpResponse(
    #         json.dumps({"nothing to see": "this isn't happening"}),
    #         content_type="application/json"
    #     )
    join_form = JoinForm(request.POST or None)
    if join_form.is_valid():
        join_form.save(commit=False)
        join_form.ip_address = get_ip(request)
        join_form.save()
        return redirect(reverse('pervasive:HomeView'))
    ''''''
    tittle = 'Pervasive | home'
    context = {
        'tittle'        : tittle,
        'join_form'     : join_form,
        'profile'       : profile,
    }
    return render(request, 'pervasive/home/home.html', context)

def product_n_services(request):
    template_name = 'pervasive/ps/product_n_services.html'
    products_results                = Product.objects.all()
    services_results                = Service.objects.all()
    tenders_results                 = Tender.objects.all()

    queryset_chain              = chain(
            products_results,
            services_results,
            tenders_results
    )
    qs                           = sorted(queryset_chain,
        key                     = lambda instance: instance.created or instance.created,
        reverse                 = True
        )
    #qs.count                  = len(qs)
    context={
        'object_list': qs,
    }
    return render(request, template_name, context)

def validate_email(request):
    email = request.GET.get('email', None)
    data = {
        'is_taken': JoinForm.objects.filter(email__iexact=email__iexact).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

templates/pervasive/footer/footer.html
<footer class="footer footer-white footer-big">
  <div class="container">
      <div class="content">
          <div class="row">
              <div class="col-md-3">
                  <a href="#pablo">
                      <h5>Pervasive Platinum</h5>
                  </a>
                  <p>Probably the best network Kit in the world! We know you've been waiting for it, so don't be shy!</p>
                  <div class="team">
                    <div class="card-profile card-plain">
                      <div class="card-footer justify-content-center">
                        <a href="#twitter" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i><div class="ripple-container"></div></a>
                        <a href="#dribbble" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                        <a href="#linkedin" class="btn btn-just-icon btn-link btn-linkedin"><i class="fa fa-linkedin"></i></a>
                        <a href="#youtube" class="btn btn-just-icon btn-link btn-youtube"><i class="fa fa-youtube-play"></i><div class="ripple-container"></div></a>
                        <a href="#instagram" class="btn btn-just-icon btn-link btn-instagram"><i class="fa fa-instagram"></i></a>
                      </div>
                    </div>
                  </div>

                </div>
              <div class="col-md-2">
                  <h5>About</h5>
                  <ul class="links-vertical" style="list-style:none;">
                      <li>
                          <a href="{% url 'blog:view_all_blogs' %}">
                              Blog
                          </a>
                      </li>
                      <li>
                          <a href="#pablo">
                              About Us
                          </a>
                      </li>
                      <!-- <li>
                          <a href="#pablo">
                              API's
                          </a>
                      </li> -->
                      <!-- <li>
                          <a href="#pablo">
                              Presentation
                          </a>
                      </li> -->
                      <li>
                          <a href="{% url 'about:plans' %}#contactusurl">
                              Contact Us
                          </a>
                      </li>
                  </ul>
              </div>
              <div class="col-md-2">
                  <h5>Market</h5>
                  <ul class="links-vertical" style="list-style:none;">
                      <li>
                          <a href="{% url 'about:faqs' %}">
                              Sales FAQ
                          </a>
                      </li>
                      <li>
                          <a href="#pablo">
                              How to Register
                          </a>
                      </li>
                      <!-- <li>
                          <a href="#pablo">
                              Sell Goods
                          </a>
                      </li>
                      <li>
                          <a href="#pablo">
                              Receive Payment
                          </a>
                      </li>
                      <li>
                          <a href="#pablo">
                              Transactions Issues
                          </a>
                      </li> -->
                  </ul>
              </div>
              <div class="col-md-2">
                  <h5>Legal</h5>
                  <ul class="links-vertical" style="list-style:none;">
                      <!-- <li>
                          <a href="#pablo">
                              Transactions FAQ
                          </a>
                      </li> -->
                      <li>
                          <a href="#pablo">
                              Terms &amp; Conditions
                          </a>
                      </li>
                      <li>
                          <a href="#pablo">
                              Cookies
                          </a>
                      </li>
                      <li>
                          <a href="#pablo">
                              Licenses
                          </a>
                      </li>
                  </ul>
              </div>
              <div class="col-md-3">
                  <h5>Subscribe to our Newsletter</h5>
                  <p>
                      Join our newsletter and get news in your inbox every week! We hate spam too, so no worries about this.
                  </p>
                  <form class="form form-newsletter" id="basecode-mailing-list" method="POST" action="" data-validate-email-url="{% url 'pervasive:validate_email' %}">
                    {% csrf_token %}
                    {{ join_form.non_field_errors }}
                    <!-- {{ form.email_errors }} -->
                    {% for field in join_form %}
                    {% if field.errors %}
                      <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
                          <span aria-hidden=true>&times;</span>
                        </button>
                         {{ field.errors }}
                      </div>
                    {% endif %}

                      <div class="form-group bmd-form-group">
                        {{ field }}
                        <!-- <input type="text" name="username" id="id_username" class="js-validate-username"> -->
                        <!-- <input class="form-control" type="email" name="email" id="id_email" value="" required=''> -->
                        <button type="submit" onclick="demo.showNotification('top','left')" class="btn btn-primary btn-sm btn-round btn-just-icon pull-right" name="submit">
                              <i class="fa fa-envelope-o"></i>
                          </button>
                      </div>
                      {% endfor %}
                  </form>
              </div>
          </div>
      </div>
      <hr>
      <div class="copyright pull-center">
          Copyright ©
          <script>
              document.write(new Date().getFullYear())
          </script> Basecode Globals Tech Inc | All Rights Reserved.
      </div>
  </div>
</footer>
<!--   Core JS Files   -->
{% block javascript %}
<script>
  $("#id_email").change(function () {
    var form = $(this).closest("form");
    var email = $(this).val();

    $.ajax({
          url: form.attr("data-validate-email-url"),
          data: form.serialize(),
          dataType: 'json',
          success: function (data) {
            if (data.is_taken) {
              alert(data.error_message);
            }
          }
        });

  });
</script>


<script>
// Submit post on submit
$('#basecode-mailing-list').on('submit', function(event){
    event.preventDefault();
    create_post();
});

// AJAX for posting
function create_post() {
    $.ajax({
        //url : "{% url 'pervasive:pervasive_view' %}", // the endpoint
        type : "POST", // http method
        data : {
            //blog_id: blog_id,
            email : $('#id_email').val(),

        }, // data sent with the post request

        // handle a successful response
        success : function(json) {
            $('#id_email').val(''); // remove the value from the input
            $('#basecode-mailing-list').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button>" + json.result +"</div>");
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#basecode-mailing-list').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button>Oop! Error happend!</div>"); // add the error to the dom
            //console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
}
</script>
{% endblock %}