basecode/urls.py
from django.urls import re_path, include, path
from django.contrib import admin
from basecode import views, settings
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from accounts.admin import admin_site
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', views.login_redirect, name='login_redirect'),
    re_path(r'^account/$', views.login_redirect, name='login_redirect'),
    #path(r'^vimage-admin/', admin.site.urls),#sys dba
    re_path(r'^pervasive-admin/', include('django_sb_admin.urls')),
    #re_path('flock-inc-admin/', admin_site.urls),#management-decision
    #re_path('flock-master-admin/', admin_site.urls),#top level-strategy
    #re_path(r'^account/', include('accounts.urls'),
    re_path(r'^account/', include('accounts.urls', namespace='accounts')),
    re_path(r'^', include('pervasive.urls', namespace='pervasive')),
    re_path(r'^finance/', include('finance.urls', namespace='finance')),
    re_path(r'^flock/', include('flock.urls', namespace='flock')),
    re_path(r'^', include('profiles.urls', namespace='profiles')),
    re_path(r'^blog/', include('blog.urls', namespace='blog')),
    re_path(r'^jobs/', include('jobs.urls', namespace='jobs')),
    re_path(r'^admanager/', include('adclass.urls', namespace='adclass')),
    re_path(r'^products/', include('products.urls', namespace='products')),
    re_path(r'^services/', include('services.urls', namespace='services')),
    re_path(r'^newsletter/', include('newsletter.urls', namespace='newsletter')),
    re_path(r'^recycle/', include('recycle.urls', namespace='recycle')),
    re_path(r'^support/', include('support.urls', namespace='support')),
    re_path(r'^drive/', include('drive.urls', namespace='drive')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    #re_path(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),


    #re_path(r'^utilities/', include('utilities.urls')),
    re_path(r'^about/', include('about.urls', namespace='about')),
    #re_path(r'^pay-pal/', include('pay-pal.urls')),
    #re_path(r'^administration/', include('administration.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

# if settings.DEBUG404:
#     urlpatterns += urlpatterns('',
#         (r'^static/(?P<path>.*)$', staticserve,
#             {'document_root': os.path.join(os.path.dirname(__file__), 'static')} ),
#         )

handler404 = views.handler404
handler500 = views.handler500

#handler403 = 'mysite.views.my_custom_permission_denied_view'
#handler403 = 'mysite.views.my_custom_permission_denied_view'

#The bad_request() view is overridden by handler400:
#handler400 = 'mysite.views.my_custom_bad_request_view'

blog/urls.py
from django.urls import re_path
from . import views
from blog.views import (
    single_blog,
    view_all_blogs,
    )

app_name='blog'

urlpatterns = [
    re_path(r'^view/(?P<slug>[\w-]+)/$', views.single_blog, name='single_blog'),
    re_path(r'^all/$', views.view_all_blogs, name='view_all_blogs'),
    # re_path(r'^view/(?P<slug>[\w-]+)/news/$', views.single_news, name='single_news'),
    re_path(r'^news/$', views.view_all_news, name='view_all_news'),
    ]

jobs/urls.py
from django.urls import re_path
from . import views
from jobs.views import (
    JobView, add_job, view_job, update_job, delete_job,
    view_all_jobs, filter_job_type, search, corp_single_job_view,
    corp_all_job_view, restore_job, remote_jobs
    #FreelancerView,
    #TenderView,

    )

app_name='jobs'

urlpatterns = [
    #user

    re_path(r'^my-jobs/$', JobView.as_view(), name='JobView'),
    re_path(r'^add/$', views.add_job, name='add_job'),
    re_path(r'^(?P<slug>[\w-]+)/update/$', views.update_job, name='update_job'),
    re_path(r'^(?P<slug>[-\w]+)/delete/$', views.delete_job, name='delete_job'),
    re_path(r'^(?P<slug>[-\w]+)/restore_job/$', views.restore_job, name='restore_job'),
    re_path(r'^(?P<slug>[\w-]+)/view/$', views.corp_single_job_view, name='corp_single_job_view'),
    #url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_job_permanent, name='delete_job_permanent'),




    re_path(r'^all$', views.view_all_jobs, name='view_all_jobs'), #visitor
    re_path(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.view_job, name='view_job'),
    #re_path(r'^all/view/$', views.corp_all_job_view, name='corp_all_job_view'), ##visitor
    re_path(r'^remote-jobs/$', views.remote_jobs, name='remote_jobs'),

    re_path(r'^filter/<job_type>$', views.filter_job_type, name='filter_job_type'),
    re_path(r'^search/$', views.search, name='search'),
    ]

jobs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F, Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView
from django.utils import timezone
from django.views.generic import TemplateView, ListView, DetailView
from itertools import chain
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User
from django.urls import reverse
from .forms import JobForm, UpdateJobForm
from jobs.models import PostJob, RePostJob
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from . stream import stream_video
from django.contrib import messages

def get_ip(request):
    try:
        x_foward = request.META.get("HTTP_X_FOWARDED_FOR")
        if x_foward:
            ip = x_foward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ''
    return ip



'''
                                   For Clients(User)
                    The views below are indented to only be used by site
                            visitors that aren't logged in
'''

#Visitor
def view_all_jobs(request):
    jobs_results                = PostJob.objects.filter(active=True).filter(deleted=False).all()
    re_jobs_results             = RePostJob.objects.filter(active=True).filter(deleted=False).all()
    queryset_chain              = chain(
             jobs_results,
             re_jobs_results,
    )
    qs                          = sorted(queryset_chain,
        key                     = lambda instance: instance.created or instance.created,
        reverse                 = True
        )
     #qs.count                  = len(qs)
    paginator = Paginator(qs, 15) # Show 25 jobs per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        qs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        qs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        qs = paginator.page(paginator.num_pages)

    context = {
        'object_list': qs,
    }
    return render(request, 'pervasive/jobs/all_jobs.html', context )

#Visitor
def view_job(request, pk, slug):
    job = list()
    try:
        job               = get_object_or_404(PostJob, pk=pk, slug=slug)
        related_job        = PostJob.objects.filter(active=True).filter(deleted=False).filter(job_type=job.job_type).all()

        '''' Record the last accessed date and number of view'''
        job.last_accessed = timezone.now()
        '''model manager function with ip address META option'''
        view_by           = get_ip(request)
        qs                = job.objects.filter(view_by__iexact=view_by).exist()
        if not qs:
        #increament job views
            job.views = F('views') + 1
            #job.update(views=F('views')+1)
            job.save()
        else: pass
        print(view_by)
    except: pass
    template_name = 'pervasive/jobs/single_job.html'
    context               = {
        'title'             : 'Job | view',
        'job'             : job,
        'related_job'             : related_job,
    }
    return render(request, template_name, context)

def remote_jobs(request):
    template_name = 'pervasive/jobs/remote_jobs.html'

    jobs_results                = PostJob.objects.filter(active=True).filter(deleted=False).filter(location='R').all()
    re_jobs_results             = RePostJob.objects.filter(active=True).filter(deleted=False).filter(location='R').all()
    queryset_chain              = chain(
             jobs_results,
             re_jobs_results,
    )
    qs                          = sorted(queryset_chain,
        key                     = lambda instance: instance.created or instance.created,
        reverse                 = True
        )

    paginator = Paginator(qs, 15) # Show 25 jobs per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        qs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        qs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        qs = paginator.page(paginator.num_pages)

    context = {
        'title'             : 'Jobs | remote',
        'object_list': qs,
    }

    return render(request, template_name, context)

def filter_job_type(request, job_type=None):
    job = list()
    try:
        job               = PostJob.objects.filter(job_type=job_type)
        '''' Record the last accessed date and number of view'''
        job.last_accessed = timezone.now()
        '''model manager function with ip address META option'''
        #job.increament
        job.last_accessed = timezone.now()
        job.save()
    except: pass
    context = {
        'job': job,
    }
    return render(request, 'jobs/job_filter.html', context)





'''
This VIEWS below are only views for the logged in user
'''

class JobView(TemplateView):
    template_name = 'profiles/jobs/all_jobs.html'

    #form = JobForm()
    def get(self, request, user =None):
        form                = JobForm()
        job                 = PostJob.objects.filter(user=request.user).filter(active=True).filter(deleted=False)

        context             = {
            'form': form,
            #"title": '{{user|capfirst - }}Jobs',
            'job': job,
        }
        return render(request, self.template_name, context)


@login_required
def add_job(request):
    template_name = 'profiles/jobs/add_job.html'
    form = JobForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect('jobs:JobView')
    #print(form.errors)
    else:
        form = JobForm(request.POST or None, request.FILES or None)

    context = {
        'form': form,
        "title": 'Jobs | add',
    }
    return render(request, template_name, context)


@require_http_methods(['GET'])
def search(request):
    query                               = request.GET.get('q')
    context                             = list()
    if query:
        object_list = PostJob.objects.active().filter(
                Q(job_icontains         = query)|
                Q(country__icontains    = query) |
                Q(city__icontains       = query)|
                Q(user__icontains       = query)|
                Q(job_type__icontains   = query)
                ).distinct().order_by('-created')
        template_name = 'jobs/job_search.html'
        context                         ={
            'object_list': object_list,
            'query': query
        }
        return render(request, template_name, context)
    return HttpResponse('Please type something.')

@login_required
def corp_all_job_view(request):
    job                 = PostJob.objects.active()
    template_name = 'profiles/jobs/all_jobs.html'
    context = {
        'job': job,
        'title': 'Jobs',
    }
    return render(request, template_name, context)

@login_required
def corp_single_job_view(request, slug=None):
    job                 = get_object_or_404(PostJob, slug=slug)
    template_name       = 'profiles/jobs/single_job_corp.html'
    context = {
        'job': job,
    }
    return render(request, template_name, context)

@login_required
def delete_job(request, slug=None):
    job             = get_object_or_404(PostJob, slug=slug)
    job.deleted     = True
    job.active      = False
    job.save()
    return redirect("jobs:JobView")

@login_required
def restore_job(request, slug=None):
    job             = get_object_or_404(PostJob, slug=slug)
    job.deleted     = False
    job.active      = True
    job.save()
    return redirect("jobs:JobView")

@login_required
def delete_job_permanent(request, slug=None):
    job = get_object_or_404(PostJob, slug=slug)
    job.delete()
    job.save()
    return redirect("jobs:JobView")

@login_required
def update_job(request, slug=None):
    job = get_object_or_404(PostJob, slug=slug)
    template_name = 'profiles/jobs/edit_job.html'
    form = UpdateJobForm(request.POST or None, request.FILES or None, instance=job)
    if form.is_valid():
        job = form.save(commit=False)
        job.edited = True
        job.last_edited = timezone.now()
        job.save()
        #messages.success(request, 'The job was successfully updated!')
        return redirect(reverse('jobs:corp_single_job_view', kwargs={'slug': job.slug}))
    else:
        form = UpdateJobForm(request.POST or None, request.FILES or None, instance=job)
        #messages.error(request, 'Please the correct errors below!')

        context = {
        "title": job.job_tittle,
        "job": job,
        "form":form,
    }
    return render(request, template_name, context)

templates/jobs/add_job.html
{% extends 'base.html' %}


  {% block body %}
  {% load humanize %}
  {% load i18n %}
  <body class="profile-page sidebar-collapse">
    {% include 'navbar.html' %}

  {% if user.userprofile.flock_cover %}
  <div class="page-header header-filter" data-parallax="true" style="background-image: url({{ user.userprofile.flock_cover.url }});"></div>
  {% else %}
  <div class="page-header header-filter" data-parallax="true" style="background-image: url('/media/media/images/defaults/bg6.jpg'); transform: translate3d(0px, 0px, 0px); color:#fff;"></div>
  {% endif %}

  <div class="main main-raised">
    <div class="profile-content">
      <ul class="timeline">

    <!-- timeline time label -->
    <li class="time-label">
        <span class="bg-red">
            10 Feb. 2014
        </span>
    </li>
    <!-- /.timeline-label -->

    <!-- timeline item -->
    <li>
        <!-- timeline icon -->
        <i class="fa fa-envelope bg-blue"></i>
        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i> 12:05</span>

            <h3 class="timeline-header"><a href="#">Support Team</a> ...</h3>

            <div class="timeline-body">

                ...
              {% trans 'Content goes here' %}
            </div>

            <div class="timeline-footer">
                <a class="btn btn-primary btn-xs">...</a>
            </div>
        </div>
    </li>
    <!-- END timeline item -->



</ul>
{% block content %}
<div class="">
  <div class="row">
    <div class="col-md-6 ml-auto mr-auto">
      <div class="profile-tabs">
        <form method='POST' id="imageContainer" action='' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
                <button type="submit" name="submit" class="btn btn-sm btn-round raised btn-primary pull-right">post</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}


      </div>
    </div>
  </div>
  {% include 'modals.html' %}
  {% include 'footer.html' %}
  <!--   Core JS Files   -->

</body>
{% endblock %}

templates/jobs/all_jobs.html
{% extends 'pervasive/base.html' %}

{% block body %}
<body class="">
  <!-- NAVIGATION MENU-->
    {% include 'nav_auth.html' %}
  <!-- END NAVIGATION -->

  <div class="wrapper">
      <!-- FIXED PLUGIN-->
        {% include 'pervasive/fixed_plugin.html' %}
      <!-- END FIXED PLUGIN -->

    <!-- LEFT SIDEBAR-->
      {% include 'pervasive/left/left_sidebar.html' %}
    <!-- END LEFT SIDEBAR -->

    <!-- TIMELINE-->
    {% block main %}
    <div class="main-panel">
      <div class="content">
        <div class="row">
          <div class="col-md-8">
            <div class="card">
            <!-- <div class="card card-white"> -->
              <div class="card-header">
                <div class="col-sm-6 text-left">
                  <h5 class="card-category">All jobs</h5>
                  <h2 class="card-title">Latest Jobs</h2>
                </div>
              </div>
              <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <!-- JOBS ON THE MAIN PAGE -->
                          <!-- ALL JOBS VIEW -->
                          <span class="current text-center container">
                          <div class="text-muted">
                            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}
                          </div>
                          </span>
                          {% for job in jobs %}
                            {% if job %}
                              <div class="card card-chart">
                                <div class="card-header">
                                  <h3 class="card-title title d-inline"><i class="tim-icons icon-badge text-primary"></i><a href="{% url 'jobs:view_job' job.pk %}">{{job.job_tittle}}</a></h3>
                                    <h5 class="card-category"><i class="tim-icons icon-tag"></i><span class="badge">{{job}} vacancy </span>
                                    <h5 class="card-category"><span class="badge">{{ job.country.name }}, {{ job.city }} <a href="{% url 'jobs:view_all_jobs'%}">jobs</a></span>
                                </div>
                                <div class="">
                                  <div class="content container">
                                      <div class="social-description ">
                                        <h4 class="card-category"><i class="tim-icons icon-credit-card"></i> <span class="badge">$-{{ job.salary_scale }}</span> </h4>
                                        <h4 class="text-muted"><i class="tim-icons icon-watch-time"></i> <span class="badge">Due in 6 days</span> </h4>
                                        <h4 class="card-category"><i class="tim-icons icon-tap-02 text-primary"></i><span class="badge">2311</span> <i class="tim-icons icon-square-pin text-primary"></i><span class="badge">3 jobs</span> <a href="{% url 'profiles:view_profile_with_pk' job.user_id %}">@{{ job.user.username }}</a></h4>
                                      </div>
                                  </div>

                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                              <!-- BOTTOM PAGINATION -->
                              {% include 'jobs/pagination.html' %}
                            <!-- END BOTTOM PAGINATION -->
                          <!-- END ALL JOBS VIEW -->
                        <div class="card-footer text-right">
                          <button type="submit" class="btn btn-fill btn-sm btn-round btn-primary">load more...</button>
                        </div>
                        <div class="content-center">
                          <div class="card-description">
                            <h2 class="description">About Pervasive jobs</h2>
                          </div>
                        </div>
                      <!-- END MAIN PAGE JOBS -->
                    </div>
                  </div>
              </div>

            </div>
          </div>
          <!-- RIGHT SIDEBAR-->
            {% include 'pervasive/right/right_sidebar.html' %}
          <!-- END RIGHT SIDEBAR -->
        </div>
      </div>
      <!-- FOOTER SIDEBAR-->
        {% include 'pervasive/footer/footer.html' %}
      <!-- END FOOTER -->
    </div>
    {% endblock %}
    <!-- END TIMELINE -->
  </div>
  <!--PERVASIVE FOOTER -->
  <!-- END FOOTER -->
</body>
{% endblock %}

templates/jobs/job_search.html
{% extends 'pervasive/base.html' %}

{% block body %}
<body class="">
  <!-- NAVIGATION MENU-->
    {% include 'nav_auth.html' %}
  <!-- END NAVIGATION -->

  <div class="wrapper">
      <!-- FIXED PLUGIN-->
        {% include 'pervasive/fixed_plugin.html' %}
      <!-- END FIXED PLUGIN -->

    <!-- LEFT SIDEBAR-->
      {% include 'pervasive/left/left_sidebar.html' %}
    <!-- END LEFT SIDEBAR -->

    <!-- TIMELINE-->
    {% block main %}
    <div class="main-panel">
      <div class="content">
        <div class="row">
          <div class="col-md-8">

            <div class="card">
            <!-- <div class="card card-white"> -->
              <div class="card-header">
                <div class="col-sm-6 text-left">
                  <h5 class="card-category">All jobs</h5>
                  <h2 class="card-title">Latest Jobs</h2>
                </div>
              </div>
              <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <!-- JOBS ON THE MAIN PAGE -->
                      <div class="container" >
                        <div class="content-center">
                          <!-- ALL JOBS VIEW -->
                          <span class="current text-center container">
                          <div class="text-muted">
                            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}
                          </div>
                          </span>
                          {% for job in jobs %}
                            {% if job %}
                              <div class="card card-chart">
                                <div class="card-header">
                                  <h3 class="card-title title d-inline"><i class="tim-icons icon-badge text-primary"></i><a href="{% url 'jobs:view_job' job.pk %}">{{job.job_tittle}}</a></h3>
                                    <h5 class="card-category"><i class="tim-icons icon-tag"></i><span class="badge">{{job}} vacancy </span>
                                    <h5 class="card-category"><span class="badge">{{ job.country.name }}, {{ job.city }} <a href="{% url 'jobs:view_all_jobs'%}">jobs</a></span>
                                </div>
                                <div class="">
                                  <div class="content container">
                                      <div class="social-description ">
                                        <h4 class="card-category"><i class="tim-icons icon-credit-card"></i> <span class="badge">$-{{ job.salary_scale }}</span> </h4>
                                        <h4 class="text-muted"><i class="tim-icons icon-watch-time"></i> <span class="badge">Due in 6 days</span> </h4>
                                        <h4 class="card-category"><i class="tim-icons icon-tap-02 text-primary"></i><span class="badge">2311</span> <i class="tim-icons icon-square-pin text-primary"></i><span class="badge">3 jobs</span> <a href="{{ job.job_owner }}">@{{ job.user }}</a></h4>
                                      </div>
                                  </div>

                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                              <!-- BOTTOM PAGINATION -->
                              {% include 'jobs/pagination.html' %}
                            <!-- END BOTTOM PAGINATION -->
                          <!-- END ALL JOBS VIEW -->
                        </div>
                        <div class="content-center">
                          <div class="card-description">
                            <h2 class="description">About Pervasive jobs</h2>
                          </div>

                        </div>

                    </div>
                      <!-- END MAIN PAGE JOBS -->
                    </div>
                  </div>
              </div>
              <div class="card-footer text-right">
                <button type="submit" class="btn btn-fill btn-sm btn-round btn-primary">load more...</button>
              </div>
            </div>
          </div>
          <!-- RIGHT SIDEBAR-->
            {% include 'pervasive/right/right_sidebar.html' %}
          <!-- END RIGHT SIDEBAR -->
        </div>
      </div>
      <!-- FOOTER SIDEBAR-->
        {% include 'pervasive/footer/footer.html' %}
      <!-- END FOOTER -->
    </div>


    {% endblock %}
    <!-- END TIMELINE -->

  </div>


  <!--PERVASIVE FOOTER -->
  <!-- END FOOTER -->
</body>
{% endblock %}
{% extends 'pervasive/base.html' %}

  {% block body %}
  {% load humanize %}
  <body class="index-page sidebar-collapse">
    <!-- NAVIGATION MENU-->
      {% include 'nav_auth.html' %}
    <!-- END NAVIGATION -->

      <div class="wrapper">
        <div class="page-header clear-filter" filter-color="orange">
            <div class="page-header-image" data-parallax="true" style="background-image: url(media/img/bg6.jpg); transform: translate3d(0px, 0px, 0px);">
            </div>

            <div class="container" >
                <div class="content-center brand ">
                  <form class="" action="jobs/search/" method="get">
                    <div class="col-sm-6 col-lg-8">
                      <div class="form-group">
                          <input type="text" value="" name="q" placeholder="Search Any Job..." class="form-control">
                      </div>
                      <button class="btn btn-info btn-round" type="submit" name="submit">Search
                      </button>
                    </div>
                  </form>
                  <h2 >Latest Jobs</h2>

                  <div class='col-sm'>
                  {% if object_list %}
                  <h5>Your search for: <strong class="badge">{{ query }}</strong></h5>
                  {% for job in object_list %}
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="img-responsive image-raised">

                        <div class="caption post-detail-item">
                          <a href="{% url 'jobs:view_job' job.pk%}">
                            <span>{{ job.user.capitalize }}-</span>
                            <span>{{ job.created|timesince }}</span>
                          </a>
                          <h3><a href=''>{{ post.job_title }}</a></h3>
                          <p><a href="{% url 'jobs:view_job' job.pk%}" class="btn btn-primary" role="button">View</a></p>
                        </div>

                      </div>
                    </div>
                  <hr/>
                  </div>
                  {% endfor %}
                  {% else  %}
                  <div class="">
                    <!-- If no results were fount, then we should just display a modal Dialog -->
                    <p>No search results were found for: <strong>{{ query }}</strong>. Please try using different keywords. </p>

                  </div>
                  {% endif %}
                  </div>
                    <ul class="pagination pagination-primary">
                        <li class="page-item">
                            <a class="page-link" href="#link" aria-label="Previous">
                                <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#link">1</a>
                        </li>
                        <li class="page-item active">
                            <a class="page-link" href="#link">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#link">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#link" aria-label="Next">
                                <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                            </a>
                        </li>
                    </ul>

                 </div>
                </div>
            </div>


            </div>
        </div>

        <div class="main">
          <!-- HERO IMAGES START -->
          {% include 'pervasive/hero_images.html' %}
          <!-- END HERO IMAGES -->

          <!-- OUR PARTNERS -->

          <!-- END PARTNERS -->


          <!-- PERVASIVE NETOWRK ABOUT SLIDE VIEWS -->
            {% include 'pervasive/pervasive_team.html' %}
          <!-- THE PERVASIVE NETOWRK AMAZING TEAM -->

        </div>

      </div>

      <!-- MODALS PLACEHOLDERS -->

      <!-- END MODALS -->


        <!--PERVASIVE FOOTER -->
        {% include 'pervasive/footer.html' %}

{% endblock %}



<div class='col-sm'>
{% if object_list %}
<h5>Your search for: <strong class="badge">{{ query }}</strong></h5>
{% for post in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="img-responsive image-raised">


        {% if post.post_image %}
         <img src='{{ post.post_image.url }}' class='img-responsive' />
        {% endif %}

      <div class="caption post-detail-item">
        <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
          <span>{{ post.user.capitalize }}</span>
          <span>{{ post.timestamp|timesince }}</span>
        </a>
        <h3><a href=''>{{ post.title }}</a></h3>
        <p><a href='{{ post.get_api_like_url }}' class='like-btn btn-link ' data-href='{{ post.get_api_like_url }}' data-likes='{{ post.likes.count }}'  href='{{ post.get_like_url }}' rel="tooltip" data-original-title="like and flock this status">{{ post.likes.count }} <i class="fa fa-heart"></i></a>
        <p><a href="" class="btn btn-primary" role="button">View</a></p>
      </div>

    </div>
  </div>
<hr/>
</div>
{% endfor %}
{% else  %}
<div class="">
  <!-- If no results were fount, then we should just display a modal Dialog -->
  <p>No search results were found for: <strong>{{ query }}</strong>. Please try using different keywords. </p>

</div>
{% endif %}
</div>